### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by psychok7** [django-push-notifications/django-push-notifications#344]
Hi there, i am running into this issue when sending a notification to multiple APNS devices using commit `fcebfc1a3c66e761f46641977106a1caee7291b0`:

```
Traceback (most recent call last):
  File "/opt/backoffice/venv/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/backoffice/venv/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/backoffice/core/tasks.py", line 121, in send_push_notifications
    None, extra=kwargs)
  File "/opt/backoffice/venv/local/lib/python2.7/site-packages/push_notifications/models.py", line 110, in send_message
    return apns_send_bulk_message(registration_ids=reg_ids, alert=message, **kwargs)
  File "/opt/backoffice/venv/local/lib/python2.7/site-packages/push_notifications/apns.py", line 268, in apns_send_bulk_message
    res = _apns_send(registration_id, alert, identifier=identifier, socket=socket, **kwargs)
  File "/opt/backoffice/venv/local/lib/python2.7/site-packages/push_notifications/apns.py", line 193, in _apns_send
    socket.write(frame)
  File "/usr/lib/python2.7/ssl.py", line 272, in write
    return self._sslobj.write(data)
error: [Errno 104] Connection reset by peer
``` 

Any ideas on what this could be or how to fix it?? I don't really have any more apns information to debug..

**Comment by PedroMD** [comment]
I think this issue needs a serious review, but you might want to take a look at your `APNS_ERROR_TIMEOUT` (check https://github.com/jleclanche/django-push-notifications/issues/95)

Also, lots of other people are sharing workarounds to solve this: https://github.com/jleclanche/django-push-notifications/issues/242

**Comment by jleclanche** [comment]
We since switched to pyapns which means this probably either doesn't happen anymore, or if it does, it's an upstream issue.
